/**
 * Copyright (c) 2014, baskingshark
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef __FILELOAD_H__
#define __FILELOAD_H__

/**
  Load a file from a device.

  The device must support the Simple File System Protocol or the Load File
  Protocol.

  @param  Device    The device from which to load the file
  @param  FilePath  Path of the file to load
  @param  Size      Location to store the size of the file
  @param  Buffer    Location to store the pointer to the data

  @retval EFI_SUCCESS           The file was loaded successfully.
  @retval EFI_OUT_OF_RESOURCES  There was insufficient memory to load the file.
  @retval EFI_NOT_FOUND         The file was not found.
  @retval EFI_INVALID_PARAMETER One or more of the parameters was invalid.
  @retval EFI_UNSUPPORTED       The device does not support any of the
                                required protocols.

  @retval ...                   Any of the errors generated by the Simple File
                                System Protocol or Load File Protocol when
                                reading files may also be returned.
 */
EFI_STATUS
EFIAPI
LoadFile(IN  EFI_HANDLE   Device,
         IN  CHAR16      *FilePath,
         OUT UINTN       *Size,
         OUT VOID       **Buffer);

/**
  Load a file from the boot device.

  Attempt to load a file from the device containing the currently loaded image.
  The device must support the Simple File System Protocol or the Load File
  Protocol.

  @param  FilePath  Path of the file to load
  @param  Size      Location to store the size of the file
  @param  Buffer    Location to store the pointer to the data

  @retval EFI_SUCCESS           The file was loaded successfully.
  @retval EFI_OUT_OF_RESOURCES  There was insufficient memory to load the file.
  @retval EFI_NOT_FOUND         The file was not found.
  @retval EFI_INVALID_PARAMETER One or more of the parameters was invalid.
  @retval EFI_UNSUPPORTED       The device does not support any of the
                                required protocols.

  @retval ...                   Any of the errors generated by the Simple File
                                System Protocol or Load File Protocol when
                                reading files may also be returned.
 */
EFI_STATUS
EFIAPI
LoadFileFromBootDevice(IN  CHAR16  *FilePath,
                       OUT UINTN   *Size,
                       OUT VOID   **Buffer);

#endif